# Generated by Django 3.1.2 on 2020-11-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_inform',
            name='ID_image',
            field=models.ImageField(null=True, upload_to=None, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='apply_inform',
            name='contact_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='apply_inform',
            name='customer_address',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AddField(
            model_name='apply_inform',
            name='customer_resident_number',
            field=models.IntegerField(default=-1),
        ),
    ]
