# Generated by Django 3.1.2 on 2020-11-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20201109_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_inform',
            old_name='customer_name',
            new_name='고객명',
        ),
        migrations.RenameField(
            model_name='apply_inform',
            old_name='customer_address',
            new_name='고객주소',
        ),
        migrations.RenameField(
            model_name='apply_inform',
            old_name='ID_image',
            new_name='신분증사진',
        ),
        migrations.RenameField(
            model_name='apply_inform',
            old_name='contact_number',
            new_name='연락처',
        ),
        migrations.RenameField(
            model_name='apply_inform',
            old_name='customer_resident_number',
            new_name='주민등록번호',
        ),
    ]
